name: Ecommerce Awards
favicon: null
layout_spectrum: 0.011300497455522418
typography_spectrum: 0.6663067676126957
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.4920313465408981
  lightness: 0.2976590672042221
  saturation: 0.822536556283012
  rhythmicContrast: 0.20807851385325193
purpose: []
